"""
Cat-qubit power, cabling, and noise utilities.

This module provides:
- Cryostat cabling models (attenuation, thermal conductance, passive heat loads)
- Hardware parameter container with derived coefficients
- Drive/interaction strength helpers and gate-time formulas
- Power accounting for pump/drive/readout
- Stim circuits for a repetition code and a noise injection pass

All temperatures are in Kelvin, frequencies in angular units (rad/s),
and powers/energies follow the conventions in the associated report/notes.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Dict, Iterable, List, Literal, Tuple, Optional, Any

import numpy as np
import scipy.optimize as scopt
from numpy.typing import NDArray
from scipy.integrate import quad
from scipy.constants import hbar, Boltzmann

from cables import cables  # cable database generated by William

# ---------------------------------------------------------------------
# Constants & Units
# ---------------------------------------------------------------------

twopi: float = 2 * np.pi
Hz, kHz, MHz, GHz = twopi, twopi * 1e3, twopi * 1e6, twopi * 1e9
us, ns = 1e-6, 1e-9
pH = 1e-12  # PicoHenry

HBAR: float = hbar
KB: float = Boltzmann

# Obélix temperatures on 03/12/2024 @ 11:08 (cold → warm)
STAGE_TEMPS: NDArray[np.float64] = np.array([0.012, 0.1, 0.97, 3.34, 35.2])
T_EXT: float = 300.0

# ---------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------


def db_to_val(dB: float | NDArray[np.float64]) -> float | NDArray[np.float64]:
    """Convert dB (power) to linear factor."""
    return 10.0 ** (dB / 10.0)


# ---------------------------------------------------------------------
# Cabling model
# ---------------------------------------------------------------------

LineType = Literal["drive", "pump", "ffl", "dc"]


@dataclass
class Line:
    """
    Represents one physical line from MXC up to 50K/RT.

    Stage ordering is assumed to match STAGE_TEMPS:
        ['MXC', '100mK', 'Still', '4K', '50K']  (cold → warm)

    Attributes
    ----------
    type : LineType
        Logical type of line (drive/pump/ffl/dc); determines stage attenuators
        and cable technologies per span.
    technology : list[str]
        Cable technology per stage span; length matches number of stages.
    lengths : np.ndarray
        Per-span lengths (m), ordered cold → warm.
    """

    type: LineType = "drive"

    # Cable technologies per span (MXC→100mK→Still→4K→50K)
    technology: List[str] = field(default_factory=list)
    lengths: NDArray[np.float64] = field(default_factory=lambda: np.flipud(
        np.array([219.29e-3, 304.04e-3, 248.64e-3, 161.58e-3, 165.88e-3])
    ))
    fixed_pads_db: Optional[NDArray[np.float64]] = None

    cable_db_keys: Dict[str, str] = field(default_factory=lambda: {
    "coax": "SC-86/50-SCN-CN",
    "dc_PhBr": "PhBr_36AWG",
    "dc_NbTi": "NbTi_36AWG",
    })

    def __post_init__(self) -> None:
        if not self.technology:
            if self.type == "dc":
                self.technology = ["dc_NbTi", "dc_NbTi", "dc_NbTi", "dc_PhBr", "dc_PhBr"]
            else:
                self.technology = ["dense", "dense", "dense", "coax", "coax"]

    @staticmethod
    def _pure_cable_attenuation_per_m(tech: str) -> float:
        """
        Return attenuation per meter (dB/m) for a cable technology.
        """
        if tech == "dense":
            # 1.5 dB/m (https://delft-circuits.com/cri-oflex-technology/core-technology-cryogenic-rf-cable/#stripline-thermal)
            return 1.5
        if tech == "coax":
            # 3.2 dB/m at 4 K (https://www.coax.co.jp/en/product/sc/086-50-scn-cn.html)
            return 3.2
        if tech in {"dc_PhBr", "dc_NbTi"}:
            # DC lines assumed to have negligible RF attenuation here.
            return 0.0
        raise ValueError(f"Unsupported cable technology: {tech!r}")

    @property
    def attenuation(self) -> NDArray[np.float64]:
        # Choose base pads: override if provided, else defaults by type
        if self.fixed_pads_db is not None:
            base = self.fixed_pads_db
        else:
            if self.type == "drive":
                base = np.array([26.0, 20.0, 10.0, 10.0, 0.0])
            elif self.type == "pump":
                base = np.array([0.0, 15.0, 13.0, 15.0, 0.0])
            elif self.type == "ffl":
                base = np.array([0.0, 0.0, 0.0, 10.0, 6.0])
            elif self.type == "dc":
                base = np.zeros(5)
            else:
                raise ValueError(f"Unsupported line type: {self.type!r}")

        cable_db = np.array([self._pure_cable_attenuation_per_m(t) for t in self.technology]) * self.lengths
        return base + cable_db

    @property
    def cumulative_attenuation(self) -> NDArray[np.float64]:
        """Cumulative attenuation up the stack (dB)."""
        return np.cumsum(self.attenuation)

    # --------------------- thermal model ---------------------

    def _get_conductance_func(self, tech: str) -> Callable[[float], float]:
        """
        Return G_eff(T) [W / (m·K)] for a given cable technology.
        """
        if tech == "coax":
            key = self.cable_db_keys.get("coax", "SC-86/50-SCN-CN")
            cable = cables.db[key]
            return lambda T: (
                cable.outer.material.k(T) * cable.outer_area
                + cable.dielectric.material.k(T) * cable.dielectric_area
                + cable.inner.material.k(T) * cable.inner_area
            )
        if tech == "dense":
            A = 1.3e-9
            return lambda T: A * 4.6 * T**0.56
        if tech == "dc_PhBr":
            key = self.cable_db_keys.get("dc_PhBr", "PhBr_36AWG")
            cable = cables.db[key]
            return lambda T: cable.inner.material.k(T) * cable.inner_area
        if tech == "dc_NbTi":
            key = self.cable_db_keys.get("dc_NbTi", "NbTi_36AWG")
            cable = cables.db[key]
            return lambda T: cable.inner.material.k(T) * cable.inner_area

        raise ValueError(f"Unsupported cable technology: {tech!r}")

    def conductance(self, T: float) -> float:
        """
        Effective thermal conductance per unit length G_eff(T) [W/(m·K)],
        using the span that sandwiches temperature T.
        """
        if T < float(np.min(STAGE_TEMPS)):
            raise ValueError("Query temperature must be ≥ MXC temperature.")

        # Determine span index (clamped to last span when T is above top stage)
        idx = int(np.searchsorted(STAGE_TEMPS, T, side="right") - 1)
        idx = max(0, min(idx, len(STAGE_TEMPS) - 1))
        tech = self.technology[idx]
        return self._get_conductance_func(tech)(T)

    def passive_heat_load(self) -> List[float]:
        """
        Passive heat per stage span [W/m], computed as:
            Q_span = ∫ G_eff(T) dT over the span
            Return Q_span / length_span (per unit length).
        """
        loads: List[float] = []
        for i, tech in enumerate(self.technology):
            T_lo = float(STAGE_TEMPS[i])
            T_hi = float(STAGE_TEMPS[i + 1]) if i < len(self.technology) - 1 else T_EXT
            G = self._get_conductance_func(tech)
            Q, _ = quad(G, T_lo, T_hi)
            loads.append(Q / self.lengths[i])
        return loads


@dataclass
class Cabling:
    stage_names: List[str] = field(default_factory=lambda: ["MXC", "100mK", "Still", "4K", "50K"])
    # Carnot factor per stage
    carnot_factors: NDArray[np.float64] = field(
        default_factory=lambda: (T_EXT - STAGE_TEMPS) / STAGE_TEMPS
    )
    lines: Dict[LineType, Line] = field(
        default_factory=lambda: {
            "drive": Line(type="drive"),
            "pump": Line(type="pump"),
            "ffl": Line(type="ffl"),
            "dc": Line(type="dc"),
        }
    )

    def Atilde(self, stage: str = "MXC", line_type: LineType = "drive") -> float:
        """
        Cumulative attenuation at a given stage (dB).
        """
        if stage not in self.stage_names:
            raise ValueError(f"Unknown stage name: {stage!r}")
        stage_index = self.stage_names.index(stage)
        return float(self.lines[line_type].cumulative_attenuation[stage_index])

    def attenuation_factors(self, line_type: LineType = "drive") -> NDArray[np.float64]:
        """
        Linear attenuation factors per span, cold → warm. For span i:
            factor[i] = lin(A_cum[i]) - lin(A_cum[i-1]),
        with factor[0] = lin(A_cum[0]).
        """
        A_cum = self.lines[line_type].cumulative_attenuation
        lin = db_to_val(A_cum)
        out = np.empty_like(lin)
        out[0] = lin[0]
        out[1:] = lin[1:] - lin[:-1]
        return out

    def M_prefactor(self, line_type: LineType = "drive") -> float:
        """
        Total 'macro' prefactor that weights chip power by the Carnot factors
        and per-stage linear attenuation contributions.
        """
        return float(np.sum(self.carnot_factors * self.attenuation_factors(line_type=line_type)))


# ---------------------------------------------------------------------
# Hardware model
# ---------------------------------------------------------------------

@dataclass
class Hardware:
    # Dissipation/linewidths (angular units)
    k_1: float = 6.97 * kHz
    k_b: float = 24 * MHz
    k_phi: float = 0.08 * MHz
    k_ext: float = 400 * Hz

    # Circuit parameters
    M: float = 2 * pH  # inductive coupling (H)
    Z: float = 50.0  # Ohm
    E_J: float = 27 * GHz * 1e-34  # J = Hz * hbar (J·s / rad)
    E_L: float = 40 * GHz * 1e-34  # J = Hz * hbar (J·s / rad)
    omega_a: float = 4.29 * GHz
    omega_b: float = 7.21 * GHz
    Phi_0: float = 2e-15  # Weber

    # Participation / lever arms
    vphi_a: float = 0.14
    vphi_b: float = 0.19
    vphi_C: float = 0.10
    vphi_T: float = 0.20

    # Thermal occupancies
    ntha: float = 0.02
    nthb: float = 0.02

    # Measurement efficiency
    eta: float = 0.4

    # Cabling
    cabling: Cabling = field(default_factory=Cabling)

    # --------------------- helpers / derived ---------------------

    def get_alpha(self, T_bf: float) -> float:
        """
        Infer alpha from a target bit-flip time T_bf using a 1D root search.
        """
        gamma_bf = 1.0 / T_bf

        def Gamma_bf(alpha: float) -> float:
            # Units are 2π rad (consistent with k_1)
            return gamma_bf - self.k_1 * alpha ** 2 * np.exp(-4 * alpha ** 2) - self.k_1 * self.ntha * np.exp(
                -2 * alpha ** 2
            )

        # Search across a grid and root-find when sign flips.
        grid = np.linspace(0.0, 10.0, 200)
        vals = Gamma_bf(grid)
        sgn = np.sign(vals)
        root = 0.0
        for i in range(len(grid) - 1):
            if sgn[i] == 0:
                root = float(grid[i])
                break
            if sgn[i] + sgn[i + 1] == 0:
                try:
                    cand = scopt.brentq(Gamma_bf, float(grid[i]), float(grid[i + 1]))
                except ValueError:
                    continue
                if np.isfinite(cand):
                    root = float(cand)
                    break
        self.alpha = root
        return root

    # Macro prefactors from cabling
    @property
    def Mp(self) -> float:
        return self.cabling.M_prefactor(line_type="pump")

    @property
    def Md(self) -> float:
        return self.cabling.M_prefactor(line_type="drive")

    @property
    def Mz(self) -> float:
        # Zeno uses drive lines in your original code
        return self.cabling.M_prefactor(line_type="drive")

    # Shared ATS-cancellation coefficient
    @property
    def generic_ATS_cancellation_coef(self) -> float:
        return self.Z * (self.Phi_0 / (2 * np.pi * self.M)) ** 2 * (1 + 4 * self.E_J ** 2 / self.E_L ** 2)

    def g_to_eps_coef(self, interaction: Literal["stab", "CNOT", "longitudinal"] = "stab") -> float:
        if interaction == "CNOT":
            return HBAR / (self.E_J * self.vphi_C * self.vphi_T ** 2)
        if interaction == "stab":
            return 2 * HBAR / (self.E_J * self.vphi_b * self.vphi_a ** 2)
        if interaction == "longitudinal":
            return HBAR / (self.E_J * self.vphi_b * self.vphi_a ** 2)
        raise ValueError(f"Unsupported interaction type: {interaction!r}")

    def ATS_cancellation_coef(self, interaction: Literal["stab", "CNOT", "longitudinal"] = "stab") -> float:
        return self.g_to_eps_coef(interaction) ** 2 * self.generic_ATS_cancellation_coef

    # Shorthand properties
    @property
    def p(self) -> float:
        return self.ATS_cancellation_coef(interaction="stab")

    @property
    def c(self) -> float:
        return self.ATS_cancellation_coef(interaction="CNOT")

    @property
    def l(self) -> float:
        return self.ATS_cancellation_coef(interaction="longitudinal")

    @property
    def d(self) -> float:
        return HBAR * self.omega_b / self.k_b

    @property
    def z(self) -> float:
        return HBAR * self.omega_a / self.k_ext

    # Bit-flip time model
    def T_bf(self, alpha: float) -> float:
        rate = self.k_1 * alpha ** 2 * np.exp(-4 * alpha ** 2) + self.k_1 * self.ntha * np.exp(-2 * alpha ** 2)
        return 1.0 / rate

    def p_z(self, alpha: float, Tgate: float) -> float:
        return alpha ** 2 * self.k_1 * Tgate * (1 + 2 * self.ntha)