from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Dict, Iterable, List, Literal, Tuple, Optional, Any

import numpy as np
import scipy.optimize as scopt
from numpy.typing import NDArray
from scipy.integrate import quad
from scipy.constants import hbar, Boltzmann

from cables import cables  # cable database generated by William
from hardware import Line, Cabling, Hardware

# ---------------------------------------------------------------------
# Constants & Units
# ---------------------------------------------------------------------

twopi: float = 2 * np.pi
Hz, kHz, MHz, GHz = twopi, twopi * 1e3, twopi * 1e6, twopi * 1e9
us, ns = 1e-6, 1e-9
pH = 1e-12  # PicoHenry

HBAR: float = hbar
KB: float = Boltzmann

# Obélix temperatures on 03/12/2024 @ 11:08 (cold → warm)
STAGE_TEMPS: NDArray[np.float64] = np.array([0.012, 0.1, 0.97, 3.34, 35.2])
T_EXT: float = 300.0

# ---------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------


def db_to_val(dB: float | NDArray[np.float64]) -> float | NDArray[np.float64]:
    """Convert dB (power) to linear factor."""
    return 10.0 ** (dB / 10.0)


# ---------------------------------------------------------------------
# Cabling model
# ---------------------------------------------------------------------

LineType = Literal["drive", "pump", "ffl", "dc"]

@dataclass
class ResCat:
    """ Class implementing the autoparametric cat qubit (Marquet 2024)"""

    # --------------------- dissipation / linewidths ---------------------
    k_1: float = 14 * kHz          # memory single-photon loss κ1 (sets ΓZ scaling)  [~14 kHz / 2π]
    k_b: float = 40 * MHz          # buffer linewidth κb (coupling to environment)   [~40 MHz / 2π]
    k_phi_m: float = 0.08 * MHz    # memory pure dephasing κφ,m                      [~0.08 MHz / 2π]

    # --------------------- mode frequencies (angular) -------------------
    omega_m: float = 3.948 * GHz   # memory frequency (so that 2ωm ≈ ωb)
    omega_b: float = 7.896 * GHz   # buffer frequency, tuned near 2 ωm

    # --------------------- three-wave-mixing ring -----------------------
    # Two main junctions (E_J) + a third ("weak") junction (E_W).
    # Store energies in Joules (so E / HBAR gives angular frequency).
    E_J: float = 228 * GHz * hbar
    E_W: float = 51  * GHz * hbar

    # Zero-point phase fluctuations across a main junction (dimensionless)
    phi_zpf_m: float = 0.0305        # memory mode zpf (φ_zpf,m)
    phi_zpf_b: float = 0.0648        # buffer  mode zpf (φ_zpf,b)
    
    # Thermal occupancies (memory & buffer)
    nth_m: float = 0.011
    nth_b: float = 0.015
    # Measurement efficiency
    eta: float = 0.4

    # Cabling
    cabling: Cabling = field(default_factory=Cabling)

    def get_alpha(self, T_bf: float) -> float:
        """
        Infer alpha from a target bit-flip time T_bf using a 1D root search.
        """
        gamma_bf = 1.0 / T_bf

        def Gamma_bf(alpha: float) -> float:
            # Units are 2π rad (consistent with k_1)
            return gamma_bf - self.k_1 * alpha ** 2 * np.exp(-4 * alpha ** 2) - self.k_1 * self.ntha * np.exp(
                -2 * alpha ** 2
            )

        # Search across a grid and root-find when sign flips.
        grid = np.linspace(0.0, 10.0, 200)
        vals = Gamma_bf(grid)
        sgn = np.sign(vals)
        root = 0.0
        for i in range(len(grid) - 1):
            if sgn[i] == 0:
                root = float(grid[i])
                break
            if sgn[i] + sgn[i + 1] == 0:
                try:
                    cand = scopt.brentq(Gamma_bf, float(grid[i]), float(grid[i + 1]))
                except ValueError:
                    continue
                if np.isfinite(cand):
                    root = float(cand)
                    break
        self.alpha = root
        return root

    # Macro prefactors from cabling
    @property
    def Mp(self) -> float:
        return self.cabling.M_prefactor(line_type="pump")

    @property
    def Md(self) -> float:
        return self.cabling.M_prefactor(line_type="drive")

    @property
    def Mz(self) -> float:
        # Zeno uses drive lines in your original code
        return self.cabling.M_prefactor(line_type="drive")
